FROM node:22.3.0 AS build
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build -- --environment CONNECT_TO:wss://modern-durak.com/wss

FROM alpine:20240606
COPY --from=0 /app/public /client